import beam_runner_api_pb from '../model/generated/beam_runner_api_pb'
import { PTransform } from '../transforms/ptransform'
import { PValue } from '../pcollection/pvalue';

/*
 * A transform node representing an instance of applying a PTransform
 * (used internally by Pipeline for bookkeeping purposes).
 */
export class AppliedPTransform {
  parent?: AppliedPTransform;
  transform?: PTransform;
  fullLabel: string;
  inputs: PValue[];
  outputs: PValue[] = [];
  parts: AppliedPTransform[] = [];

  /** Ref generated by PipelineContext */
  ref: string = "";

  constructor(parent: AppliedPTransform | undefined, transform: PTransform | undefined, fullLabel: string, inputs: PValue[]) {
    this.parent = parent;
    this.transform = transform;
    this.fullLabel = fullLabel;
    this.inputs = inputs;
  }

  addPart(part: AppliedPTransform) {
    this.parts.push(part);
  }

  addOutput(output: PValue) {
    this.outputs.push(output);
  }

  serialize() {
    const transform = new beam_runner_api_pb.PTransform();
    if (this.fullLabel !== "") {
      transform.setUniqueName(this.fullLabel);
    }
    if (this.transform) {
      transform.setSpec(this.transform.serialize());
      for (let i in this.inputs) {
        transform.getInputsMap().set(i, this.inputs[i].ref);
      }
      for (let i in this.outputs) {
        // TODO: handle multiple outputs
        transform.getOutputsMap().set("None", this.outputs[i].ref);
      }
      // TODO:
      // setInputs
      // setOutputs
    } else {
      // is root transform
    }
    // TODO: don't use fullLabel here; use the ref from the context instead.
    transform.setSubtransformsList(this.parts.map(part => part.ref));
    return transform;
  }
}